### ISSUE TITLE
It never emits "success" event 

### ISSUE THREAD

**Issue by pmhegdek** [deanWombourne/node-diawi#4]
It only emits "complete" event.

**Comment by deanWombourne** [comment]
I'm afraid I don't understand why this is an issue? "complete" == "success"? Is there a standard for events I should be aware of?

**Comment by ghost** [comment]
The docs at npmjs.org mention this as an example of use
`new Diawi({ token: "api token", path: "path/to/app.ipa" }).on("success", function(url) { ... }).on("error", function(error) { ... })
:`

If the correct event name is "complete", then the docs at npmjs.org should reflect it.

**Comment by deanWombourne** [comment]
Yep, totally my mistake, sorry about that! I've merged your fix (#6) :)
